project_id = "xwfzrbigmgyxsrzlkqwr"

[functions.create-company]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.assign-plan]
verify_jwt = true

[functions.freeze-company]
verify_jwt = true

[functions.check-subscription-health]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.create-super-admin]
verify_jwt = false

[functions.create-platform-admin]
verify_jwt = false
