project_id = "xwfzrbigmgyxsrzlkqwr"

[functions.create-company]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.assign-plan]
verify_jwt = true

[functions.freeze-company]
verify_jwt = true

[functions.check-subscription-health]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.create-super-admin]
verify_jwt = false

[functions.create-platform-admin]
verify_jwt = false

[functions.check-platform-admin]
verify_jwt = false

[functions.check-suspicious-login]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false

[functions.check-email-secrets]
verify_jwt = false

[functions.send-webhook]
verify_jwt = false

[functions.request-multi-company]
verify_jwt = true

[functions.request-trial-extension]
verify_jwt = true

[functions.send-trial-expiration-emails]
verify_jwt = false

[functions.create-employee-user]
verify_jwt = false
